### ISSUE TITLE
Rename respelling -> resize (or scale?)

### ISSUE THREAD

**Issue by mossheim** [dn-m/ArithmeticTools#119]
making a fraction have a larger denominator is "expanding"; the inverse is "reducing". so, the name for an operation that either expands or reduces might be better expressed as something with a spatial connotation, like "resize" or "scale" (or "scaleTo"? seems verbose)

**Comment by jsbean** [comment]
I think I vote for `scale(denominator:)` and `scale(numerator:)`.

The only issue is, is that it feels like it is actually changing size. However, it should be explicit that the underlying arithmetic value is the same.

**Comment by mossheim** [comment]
Ok, that makes sense to me. I guess the name fits since you're technically multiplying n & d by scalars. :)

**Comment by jsbean** [comment]
In related news, what about `mutate`.

I was trying to differentiate the two methods (one where the original arithmetic value is maintained, and one where it is corrupted).

It could be nice to have a pair of names that are polar in the same field.

**Comment by mossheim** [comment]
i think maintain/corrupt isn't an atomic enough pair to base the names on. many operations can maintain the value, and many operations can corrupt it.
