### ISSUE TITLE
Fill out tests

### ISSUE THREAD

**Issue by jsbean** [dn-m/ArithmeticTools#23]
We are at ca. 60% test coverage. Let's get the remaining bits of this tested.

**Comment by mossheim** [comment]
#86 and #87 are improvements to this.

**Comment by mossheim** [comment]
I'm not sure on the stability of other recent additions like `CategoryTheory`, or how to test them.

**Comment by jsbean** [comment]
Yeah, I wouldn't worry about that. That is more an interface than anything. The whole point of the `Monoid` is that you can run `reduce` on a container of it:

```Swift
let arrayOfInts = [1,2,3,4]
let sum = arrayOfInts.reduce(0) { $0 + $1 } // or,
let sum = arrayOfInts.reduce(0, +) // or,
let sum = arrayOfInts.reduce(.unit, +)
```

So, in this case, we can also do this over `MetricalDurations` (or any `Rational` type), and anything else that has these two traits:

```Swift
let durs = [1/>4, 3/>16, 17/>64]
let sum = durs.reduce(.unit, +)
```

These are the trivial examples, but this whole thing also helps to unify the numeric types in the context of a `Sequence`.

**Comment by mossheim** [comment]
ok! do we have an annotation to mark something as do-not-test for code coverage? or is that just plain out?

**Comment by jsbean** [comment]
I can't find any annotation for codecov. I'd say this is where we are just fine with <100% coverage.

**Comment by mossheim** [comment]
ok! i'll try to get more tests done and maybe have this closed by tomorrow

**Comment by mossheim** [comment]
We're at 89% coverage now; most of the remaining uncovered cases are initializers and aliases for basic math ops. I'm gonna close this if that's ok :)

**Comment by jsbean** [comment]
Absolutely!
