### ISSUE TITLE
Implement isPowerOfTwoWith(coefficient coefficient: Self) -> Bool

### ISSUE THREAD

**Issue by jsbean** [dn-m/ArithmeticTools#3]
``` Swift
12.isPowerOfTwoWith(coefficient: 3) // true
15.isPowerOfTwoWith(coefficient: 3) // false
```

**Comment by mossheim** [comment]
What is the use case for this method?

**Comment by jsbean** [comment]
Verification of values in tuplets such as:

- `13:12`

or time signatures:

- `5/28`

**Comment by jsbean** [comment]
That being said, the API should read:

```Swift
func isPowerOfTwo(coefficient: Self = 2) -> Self
```

**Comment by jsbean** [comment]
But that being said, I don't think this is urgent, nor necessarily advisable now.

I'm gonna close this.

**Comment by mossheim** [comment]
Ok! Seems like this could be just as useful:
```swift
func factors() -> [Integer]
```

**Comment by jsbean** [comment]
Oh, absolutely !

**Comment by jsbean** [comment]
See #24.
