### ISSUE TITLE
Resolve naming discrepancy in IntervalRelation

### ISSUE THREAD

**Issue by mossheim** [dn-m/ArithmeticTools#89]
All IntervalRelations are CustomStringConvertible to their exact name except for `.contains`, which is converted to `"during"`. Which should we use?

**Comment by mossheim** [comment]
Oops, I mean `.containedBy`

**Comment by jsbean** [comment]
Ahh beautiful! Yes, I updated the actual case, but not the `description`.

In the original Allen Interval Algebra, the terminology `during` is used. However, that seems very temporality-centric, though these ranges are not tied to temporality.
