### ISSUE TITLE
Add range mapping functions

### ISSUE THREAD

**Issue by mossheim** [dn-m/ArithmeticTools#98]
Similar to SuperCollider's `linexp`, `linlin`, etc. These functions take 5 values: `x`, the value to be mapped, and two pairs of ranges. `x` is treated as a relative position in the first range and mapped to its relative position in the second range.

`5.linlin(0, 10, 10, 20)` -> `15`
`5.linlin(0, 20, 10, 20)` -> `12.5`
`10.linlin(0, 10, 10, 20)` -> `20`

`5.linexp(0, 10, 10, 20)` -> `14.142135623731`

**Comment by mossheim** [comment]
If we had these, I would be able to abstract a good portion of easing logic.

**Comment by jsbean** [comment]
For reference, I would say we should add this point of configuration within [`scaled(from:to:)`](https://github.com/dn-m/ArithmeticTools/blob/7e4653662c136bdb5c168e05e2ad9f838fb1752e/ArithmeticTools/BinaryFloatingPointExtensions.swift#L28).
